add support for configurable non-locking sessions
zendframework/zend-expressive-session-ext pull request #43
Opened 2019-03-06 02:45 UTC by pine3ree

**Note:**
This is a port of my local implementation (which now differs a little from this repo), so I'll let it sit here for other developers tests and suggestions. I possibly forgot to port something at this late hour.

_Short explaination:_
- basically, if we have a session cookie in the request we open the session file and close it right after reading it with the php-documented `read_and_close` option. 
- In the persistSession phase, with the `non_locking` option "on" the session (file) is closed (see test cases): if the session is regenerated or we didn't have an initial opened session, the session is already (re)generated by previous code, so I added an "elseif" checking for the nonLocking property and if the session data changed, because we do not need to open the session file if there are no changes to write.
- I could have left the session status off (`session_write_close' C code does that itself), but I believe this remind the developers that the session could be not active at that point, if there is no need for it to be so.

**TODO**
- add warnings and caveats (docs) about what can go wrong with non-locking sessions and advice users about when this option could be (more) safely utilized (session file locking was added for a reason!)
- translate configuration documentation from php-doc blocks into md docs
- test, test, test...

2019-03-06 19:16 UTC, pine3ree commented
I forgot to mention an important aspect. Assume we have 2 scripts started by the same client (read "same session id"), right now the behaviour is the following:
```
script 1 start
    read-and-close session(state=1)
    alter session(state=2)
    
    script 2 start
        read-and-close session(state=1) (it can now since is not locked)
        alter session(state=3) data
        persist session(state=3) data
    script 2 end
    
    reopen session(state=3)
    persist session(state=2) data (state 3 is lost)
script 1 end    
```

Originally I made the last persiste do this:
```
persist session(state=2) data + session(state=3) data
```
in php code:
```php
$_SESSION = $session->toArray() + $_SESSION; // this is the data read from the last reading/reopening)
```
the first script accessing the same session data have precedence when persisting data over other scripts, but other scripts changes MAY be included as well.
But then we may have cases when the first script deletes some keys and then those same keys will find their way back into the persisted data because of the last assignment. So i kept things simple and save only the state from the script point of view. As I said, session locking is there for a reason, and there is no way to handle concurrent changes in a clean way. WIth this implementation we are only sure that the last script that writes the session wins....

2019-03-12 13:47 UTC, weierophinney requested changes
Overall, this makes sense.

So, the key here is: provide some documentation, please. :smile: Current docs are in the `docs/book/` tree; you can either add to the `intro.md` file (which has a configuration section), or you can provide a new document (if you do, add it to the `mkdocs.yml` TOC!).

2019-03-12 13:54 UTC, froschdesign commented
@pine3ree 
You can also ping me if you need help with the documentation.

2019-03-12 15:50 UTC, pine3ree commented
Hello @weierophinney , @froschdesign,

would this be ok (as an h3 inside the h2 configuration doc)

### Activating non locking sessions

The default behaviour of the php session extension is to lock the session file
until *session_write_close* is called - usually at the end of script execution -
in order to safely store the session data. This has the side effect of blocking
every other script that request access to the same session file as for instance
in ajax calls in a Single Page Application. The php session extension allows us
to unlock the session file using the extra option *read_and_close* in *session_start*.
This option can be activated using the following configuration:

```php
// file: data/session.global.php
return [
    'session' => [
        'persistence' => [
            'ext' => [
                'non_locking' => true, // true|false, true => read_and_close = true
            ],
        ],
    ],
];
```

As for the php extension, we can use safely use this option only when we are sure
that the session data won't be changed or when only one of the concurrent scripts
may change it. The last script that change and persist the session data will
overwrite any previous change.

I may add a commit for this, or you may use it a a starting point for a "true" english documentation entry.

Do you reckon that we should add constants such as
```
SessionInterface::CONFIG_KEY = 'session';
SessionPersistentInterface::CONFIG_KEY = 'persistence';
PhpSessionPersistentInterface::CONFIG_KEY = 'ext';
```
?  It is technically correct, but maybe a little overdone. Maybe we just skip that, what do you think?

(unrelated) PS
pinging @weierophinney, just to avoid to ping you from another repo. I added a proof-of-concept implementation for session that always creates a sid even without any data access, liks session_start does https://github.com/zendframework/zend-expressive-session-ext/issues/23#issuecomment-471360942.

2019-04-30 20:10 UTC, weierophinney commented
> I may add a commit for this, or you may use it a a starting point for a "true" english documentation entry.

Please add a commit for that, and I think we're ready.

Regarding the constants... let's revisit that in a later PR, maybe. :smile:

2019-04-30 20:55 UTC, pine3ree commented
@weierophinney 
> Please add a commit for that, and I think we're ready.

Already added here https://github.com/zendframework/zend-expressive-session-ext/pull/43/commits/44a995a7211c8274880db6cedc05a1d84ba0ac04,
kind regards

2019-04-30 21:01 UTC, weierophinney approved these changes

2019-10-16 15:12 UTC, merged

2019-10-16 15:12 UTC, weierophinney commented
Thanks, @pine3ree !